export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_BY_NAME = 'GET_COUNTRIES_BY_NAME';
export const GET_COUNTRIES_BY_REGION = 'GET_COUNTRIES_BY_REGION';
export const GET_COUNTRY_BY_NAME = 'GET_COUNTRY_BY_NAME';
export const SET_LOADING = 'SET_LOADING';
export const RESET_COUNTRY = 'RESET_COUNTRY';
export const GET_CURRENT_COUNTRIES = 'GET_CURRENT_COUNTRIES';
export const GET_TOTAL_COUNTRIES = 'GET_TOTAL_COUNTRIES';